version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y

  provaconceitoapi:
    image: ${DOCKER_REGISTRY-}provaconceitoapi
    build:
      context: .
      dockerfile: ProvaConceitoApi/Dockerfile
