version: '3.4'

services:
  sqldata:
    container_name: sqlserver
    environment:
      - SA_PASSWORD=!Admin123*
    ports:
      - 5414:1433
    volumes:
      - provaconceito_sqldata:/var/opt/mssql

  provaconceitoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  provaconceito_sqldata:
    external: false